services:
  kaggle-asl-fingerspelling:
    build: ./Dockerfile
    container_name: kaggle-asl-fingerspelling
    hostname: kaggle-asl-fingerspelling
    shm_size: '28gb'
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             capabilities: ["gpu"]
    volumes:
      - ${PWD}/:/workspace:cached
      - ${PWD}/kaggle:/kaggle:cached
      - ${MLFLOW_STORAGE_PATH}:/workspace/log/mlruns
    environment:
      TZ: Asia/Tokyo
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}
      KAGGLE_KEY: ${KAGGLE_KEY}
      MLFLOW_TRACKING_URI: /workspace/log/mlruns
    tty: true
